# Generated by Django 5.2.16 on 2026-07-13 20:46

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('deactivated_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.CharField(blank=True, max_length=1000)),
            ],
            options={
                'ordering': ('-started_at',),
                'permissions': (('manage_jackrabbit_sync', 'Can run and diagnose Jackrabbit class synchronization'),),
            },
        ),
        migrations.CreateModel(
            name='JackrabbitClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(db_index=True, max_length=20)),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=240)),
                ('description', models.TextField(blank=True)),
                ('category1', models.CharField(blank=True, max_length=160)),
                ('category2', models.CharField(blank=True, max_length=160)),
                ('category3', models.CharField(blank=True, max_length=160)),
                ('gender', models.CharField(blank=True, max_length=40)),
                ('instructors', models.JSONField(blank=True, default=list)),
                ('location_code', models.CharField(blank=True, max_length=80)),
                ('location_name', models.CharField(blank=True, max_length=160)),
                ('location_address1', models.CharField(blank=True, max_length=200)),
                ('location_address2', models.CharField(blank=True, max_length=200)),
                ('location_city', models.CharField(blank=True, max_length=120)),
                ('location_state', models.CharField(blank=True, max_length=80)),
                ('location_postal_code', models.CharField(blank=True, max_length=30)),
                ('location_phone', models.CharField(blank=True, max_length=40)),
                ('room', models.CharField(blank=True, max_length=120)),
                ('session', models.CharField(blank=True, max_length=160)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('registration_start_date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('meeting_days', models.JSONField(blank=True, default=dict)),
                ('minimum_age', models.CharField(blank=True, max_length=40)),
                ('maximum_age', models.CharField(blank=True, max_length=40)),
                ('is_per_day', models.BooleanField(default=False)),
                ('waitlist', models.BooleanField(blank=True, null=True)),
                ('calculated_openings', models.IntegerField(blank=True, null=True)),
                ('openings_by_day', models.JSONField(blank=True, default=dict)),
                ('tuition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tuition_by_day', models.JSONField(blank=True, default=dict)),
                ('billing_cycle', models.CharField(blank=True, max_length=120)),
                ('online_registration_url', models.URLField(blank=True, max_length=1000)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('category1', 'name', 'start_time'),
                'indexes': [models.Index(fields=['organization_id', 'is_current'], name='jr_class_org_current'), models.Index(fields=['session', 'location_code'], name='jr_class_session_loc')],
                'constraints': [models.UniqueConstraint(fields=('organization_id', 'external_id'), name='unique_jackrabbit_class')],
            },
        ),
        migrations.CreateModel(
            name='JackrabbitEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_id', models.CharField(db_index=True, max_length=20)),
                ('event_type', models.CharField(choices=[('family_created', 'Family created'), ('contact_created', 'Contact created'), ('student_created', 'Student created'), ('lead_created', 'Lead created'), ('student_enrolled', 'Student enrolled'), ('student_dropped', 'Student dropped'), ('waitlist_added', 'Student added to waitlist'), ('waitlist_removed', 'Student removed from waitlist'), ('student_inactive', 'Student inactive')], db_index=True, max_length=32)),
                ('source', models.CharField(choices=[('trigger', 'Zapier trigger'), ('backfill', 'Zapier search backfill')], default='trigger', max_length=16)),
                ('dedupe_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('family_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('contact_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('student_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('class_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('enrollment_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=160)),
            ],
            options={
                'ordering': ('-occurred_at', '-received_at'),
                'permissions': (('view_reporting_dashboard', 'Can view the Jackrabbit reporting dashboard'),),
                'indexes': [models.Index(fields=['event_type', 'occurred_at'], name='jr_event_type_date'), models.Index(fields=['organization_id', 'occurred_at'], name='jr_event_org_date')],
            },
        ),
    ]
