# Generated by Django 5.2.16 on 2026-07-10 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_seed_editable_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='cancellation_url',
            field=models.URLField(blank=True, help_text='Optional link to the approved cancellation and refund policy.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='footer_credentials',
            field=models.CharField(default='USA Gymnastics & AAU Member • Jacksonville, Florida', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='header_button_text',
            field=models.CharField(default='Try a class', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_benefit_one',
            field=models.CharField(default='Secure Stripe checkout', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_benefit_three',
            field=models.CharField(default='Annual registration fee may apply', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_benefit_two',
            field=models.CharField(default='Class placement confirmed separately', max_length=160),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_link_note',
            field=models.CharField(default='After placement is confirmed, the office will email a private payment link.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_page_checkout_label',
            field=models.CharField(default='Continue to secure Stripe checkout', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_page_completed_note',
            field=models.CharField(default='This payment has been completed.', max_length=200),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_page_eyebrow',
            field=models.CharField(default='Office-confirmed payment', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_page_security_note',
            field=models.CharField(default='Card information is entered directly on Stripe and is never stored by Gyminators.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_page_unavailable_note',
            field=models.CharField(default='This payment link is no longer available. Please contact the office.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_processing_message',
            field=models.CharField(default='Your payment is still processing. Gyminators will confirm it by email.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_success_message',
            field=models.CharField(default='Payment confirmed. Gyminators will contact you to confirm the account update.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='privacy_url',
            field=models.URLField(blank=True, help_text='Optional link to the approved privacy policy.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='terms_url',
            field=models.URLField(blank=True, help_text='Optional link to the approved website or payment terms.'),
        ),
    ]
