# Generated by Django 5.2.16 on 2026-07-10 20:41

from django.db import migrations, models


def ensure_legacy_billing_is_empty(apps, schema_editor):
    model_names = ("MembershipPlan", "Customer", "Subscription", "Payment", "PaymentRequest", "WebhookEvent")
    populated = {
        model_name: apps.get_model("website", model_name).objects.count()
        for model_name in model_names
        if apps.get_model("website", model_name).objects.exists()
    }
    if populated:
        details = ", ".join(f"{name}: {count}" for name, count in populated.items())
        raise RuntimeError(
            "Jackrabbit migration stopped because legacy Stripe records still exist "
            f"({details}). Export and reconcile them, stop any live Stripe billing, "
            "then clear the retired local records before retrying."
        )


def update_default_payment_copy(apps, schema_editor):
    SiteConfiguration = apps.get_model("website", "SiteConfiguration")
    replacements = {
        "registration_url": (
            "https://app.jackrabbitclass.com/regv2.asp?id=154877",
            "https://app3.jackrabbitclass.com/regv2.asp?id=154877",
        ),
        "payment_eyebrow": ("Secure online payments", "Jackrabbit registration & billing"),
        "payment_heading": ("Pay with confidence.", "Classes and payments in one place."),
        "payment_body": (
            "Use online checkout only after the Gyminators office confirms class placement. Registration, waivers, and class selection are completed separately.",
            "Gyminators uses Jackrabbit for registration, enrollment, family accounts, policies, and payments.",
        ),
        "payment_benefit_one": ("Secure Stripe checkout", "Enroll in classes and events"),
        "payment_benefit_two": ("Class placement confirmed separately", "Review charges and payment history"),
        "payment_benefit_three": ("Annual registration fee may apply", "Manage policies and family details"),
        "payment_portal_note": (
            "After placement is confirmed, the office will email a private payment link.",
            "New families begin with Online Registration. Existing families should use their Parent Portal account.",
        ),
    }
    for site in SiteConfiguration.objects.all():
        changed = []
        for field_name, (old_value, new_value) in replacements.items():
            if getattr(site, field_name) == old_value:
                setattr(site, field_name, new_value)
                changed.append(field_name)
        if changed:
            site.save(update_fields=changed)


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_editable_business_copy'),
    ]

    operations = [
        migrations.RunPython(ensure_legacy_billing_is_empty, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='subscription',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='membershipplan',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='subscription',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='cancelled_by',
        ),
        migrations.RemoveField(
            model_name='paymentrequest',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='WebhookEvent',
        ),
        migrations.DeleteModel(
            name='ReportingPermission',
        ),
        migrations.RenameField(
            model_name='siteconfiguration',
            old_name='payment_link_note',
            new_name='payment_portal_note',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_page_checkout_label',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_page_completed_note',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_page_eyebrow',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_page_security_note',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_page_unavailable_note',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_processing_message',
        ),
        migrations.RemoveField(
            model_name='siteconfiguration',
            name='payment_success_message',
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='class_schedule_url',
            field=models.URLField(default='https://app.jackrabbitclass.com/jr3.0/Openings/OpeningsDirect?OrgID=154877'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='jackrabbit_owner_url',
            field=models.URLField(default='https://app.jackrabbitclass.com/jr4.0/Login'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_existing_body',
            field=models.TextField(default='Use the Parent Portal to view your balance, make payments, manage billing information, and enroll in available programs.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_existing_button',
            field=models.CharField(default='Open Parent Portal', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_existing_heading',
            field=models.CharField(default='Current families', max_length=120),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_new_body',
            field=models.TextField(default='Create your family account, choose a class or trial, complete required policies, and provide billing details in Jackrabbit.'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_new_button',
            field=models.CharField(default='Register with Jackrabbit', max_length=80),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='payment_new_heading',
            field=models.CharField(default='New families', max_length=120),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_portal_note',
            field=models.CharField(default='New families begin with Online Registration. Existing families should use their Parent Portal account.', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='staff_portal_url',
            field=models.URLField(default='https://app.jackrabbitclass.com/jr3.0/TimeClock/StaffLogin?orgId=154877'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_benefit_one',
            field=models.CharField(default='Enroll in classes and events', max_length=160),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_benefit_three',
            field=models.CharField(default='Manage policies and family details', max_length=160),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_benefit_two',
            field=models.CharField(default='Review charges and payment history', max_length=160),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_body',
            field=models.TextField(default='Gyminators uses Jackrabbit for registration, enrollment, family accounts, policies, and payments.'),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_eyebrow',
            field=models.CharField(default='Jackrabbit registration & billing', max_length=120),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='payment_heading',
            field=models.CharField(default='Classes and payments in one place.', max_length=160),
        ),
        migrations.AlterField(
            model_name='siteconfiguration',
            name='registration_url',
            field=models.URLField(default='https://app3.jackrabbitclass.com/regv2.asp?id=154877'),
        ),
        migrations.RunPython(update_default_payment_copy, migrations.RunPython.noop),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='MembershipPlan',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
