# Generated by Django 5.2.16 on 2026-07-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_siteconfiguration_show_online_waiver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfiguration',
            name='show_online_waiver',
            field=models.BooleanField(default=False, help_text='The current Regular and Camp wording is legally approved and must remain unchanged; any text or version change requires renewed legal review. Add the approved privacy policy URL and complete the retention and security checks before enabling.'),
        ),
    ]
