# Generated by Django 5.2.16 on 2026-07-16 16:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GymnastProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(db_index=True, max_length=100)),
                ("date_of_birth", models.DateField(db_index=True)),
                ("age", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ("last_name", "first_name"),
                "indexes": [models.Index(fields=["last_name", "date_of_birth"], name="waiver_gym_last_dob_idx")],
            },
        ),
        migrations.CreateModel(
            name="GuardianProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=40)),
                ("phone_digits", models.CharField(db_index=True, editable=False, max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("occupation", models.CharField(blank=True, max_length=160)),
                ("work_phone", models.CharField(blank=True, max_length=40)),
                ("cell_phone", models.CharField(blank=True, max_length=40)),
                ("second_guardian_name", models.CharField(blank=True, max_length=200)),
                ("second_guardian_occupation", models.CharField(blank=True, max_length=160)),
                ("second_guardian_work_phone", models.CharField(blank=True, max_length=40)),
                ("second_guardian_cell_phone", models.CharField(blank=True, max_length=40)),
                ("gymnast", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="guardian", to="waivers.gymnastprofile")),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyContactProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("relationship", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=40)),
                ("phone_digits", models.CharField(db_index=True, editable=False, max_length=30)),
                ("gymnast", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="emergency_contact", to="waivers.gymnastprofile")),
            ],
        ),
        migrations.CreateModel(
            name="AuthorizedPickupProfile",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("phone", models.CharField(max_length=40)),
                ("phone_digits", models.CharField(db_index=True, editable=False, max_length=30)),
                ("gymnast", models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name="authorized_pickup", to="waivers.gymnastprofile")),
            ],
        ),
        migrations.CreateModel(
            name="ReturningSearchThrottle",
            fields=[
                ("client_key", models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ("window_started_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "returning-waiver search throttle",
                "verbose_name_plural": "returning-waiver search throttles",
                "indexes": [models.Index(fields=["updated_at"], name="waiver_throttle_updated_idx")],
            },
        ),
        migrations.CreateModel(
            name="WaiverSubmissionThrottle",
            fields=[
                ("client_key", models.CharField(editable=False, max_length=64, primary_key=True, serialize=False)),
                ("window_started_at", models.DateTimeField()),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "waiver submission throttle",
                "verbose_name_plural": "waiver submission throttles",
                "indexes": [models.Index(fields=["updated_at"], name="waiver_submit_updated_idx")],
            },
        ),
        migrations.CreateModel(
            name="Waiver",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("participant_status", models.CharField(choices=[("new", "New gymnast"), ("returning", "Returning gymnast")], max_length=12)),
                ("enrollment_type", models.CharField(choices=[("regular", "Regular enrollment"), ("camp", "Camp enrollment")], max_length=12)),
                ("activity_name", models.CharField(blank=True, max_length=200)),
                ("typed_signer_name", models.CharField(max_length=200)),
                ("signer_capacity", models.CharField(choices=[("parent", "Parent"), ("legal_guardian", "Legal guardian")], max_length=20)),
                ("pickup_verified", models.BooleanField(default=False)),
                ("agreement_accepted", models.BooleanField()),
                ("agreement_version", models.CharField(max_length=100)),
                ("agreement_sha256", models.CharField(editable=False, max_length=64)),
                ("legal_text_snapshot", models.TextField()),
                ("initials", models.JSONField()),
                ("details", models.JSONField()),
                ("signature_png", models.BinaryField()),
                ("signature_sha256", models.CharField(editable=False, max_length=64)),
                ("submission_key", models.CharField(editable=False, max_length=64, unique=True)),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("authorized_pickup", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="waivers.authorizedpickupprofile")),
                ("emergency_contact", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="waivers.emergencycontactprofile")),
                ("guardian", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to="waivers.guardianprofile")),
                ("gymnast", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="waivers", to="waivers.gymnastprofile")),
            ],
            options={
                "ordering": ("-signed_at",),
                "indexes": [
                    models.Index(fields=["signed_at"], name="waiver_signed_at_idx"),
                    models.Index(fields=["enrollment_type", "signed_at"], name="waiver_type_signed_idx"),
                    models.Index(fields=["gymnast", "signed_at"], name="waiver_gym_signed_idx"),
                ],
                "constraints": [models.CheckConstraint(condition=models.Q(("agreement_accepted", True)), name="waiver_agreement_required")],
            },
        ),
    ]
