# Generated by Django 5.2.16 on 2026-07-16 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredWaiverPDF',
            fields=[
                ('waiver', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='stored_pdf', serialize=False, to='waivers.waiver')),
                ('pdf_bytes', models.BinaryField()),
                ('pdf_sha256', models.CharField(editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text="When this exact artifact was generated; for a legacy backfill this is later than the waiver's signed timestamp.")),
            ],
            options={
                'verbose_name': 'stored signed-waiver PDF',
                'verbose_name_plural': 'stored signed-waiver PDFs',
            },
        ),
    ]
